#pragma once
#include <string>
#include <string_view>
#include <vector>
#include <array>
#include <utility>
#include <format>
#include <iostream>
#include <fstream>
#include <stdexcept>
#include <limits>
#include <cstdint>
#include <glm/glm.hpp>
#include <glad/gl.h>
#include <nlohmann/json.hpp>
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#define IMGUI_DEFINE_MATH_OPERATORS
#include <imgui.h>
#include <backends/imgui_impl_glfw.h>
#include <backends/imgui_impl_opengl3.h>